import sys
import tempfile
import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CORE_PATH = PROJECT_ROOT / "moko_core"
DOCS_PATH = Path(__file__).resolve().parent
if str(CORE_PATH) not in sys.path:
    sys.path.insert(0, str(CORE_PATH))
# Template Learning Engine berada di paket riset (docs).
if str(DOCS_PATH) not in sys.path:
    sys.path.insert(0, str(DOCS_PATH))

try:
    from moko_agents.software_builder.playground_worker import PlaygroundWorker, PlaygroundSession
    _IMPORT_ERROR = None
except ModuleNotFoundError as import_error:
    PlaygroundWorker = None
    PlaygroundSession = None
    _IMPORT_ERROR = import_error


@unittest.skipIf(_IMPORT_ERROR is not None, f"Dependensi tidak tersedia: {_IMPORT_ERROR}")
class PlaygroundWorkerServerGateTest(unittest.TestCase):
    def _new_worker(self, instruction: str = "buat kalkulator") -> PlaygroundWorker:
        worker = PlaygroundWorker(instruction=instruction, language="python")
        worker.session = PlaygroundSession()
        return worker

    def test_offline_server_recovery_failed_must_error_and_auto_close(self) -> None:
        worker = self._new_worker()
        try:
            errors: list[str] = []
            worker.error_signal.connect(errors.append)
            worker._check_server_online = lambda: (False, "offline")
            worker._attempt_server_recovery = lambda: (False, "offline")
            worker._call_llm = lambda _prompt: "SHOULD_NOT_BE_CALLED"

            worker._run_playground()

            self.assertFalse(worker.session.is_active)
            self.assertEqual("", worker.session.main_file)
            self.assertEqual("", worker.session.code)
            self.assertTrue(errors)
            self.assertIn("tidak online", errors[-1].lower())
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_offline_server_recovery_success_continue_generation(self) -> None:
        worker = self._new_worker()
        try:
            state = {"recover_called": False}
            worker._check_server_online = lambda: (False, "offline")

            def _recover():
                state["recover_called"] = True
                return True, "ok"

            worker._attempt_server_recovery = _recover
            worker._call_llm = lambda _prompt: "```python\nprint('recovered online')\n```"
            worker._capture_learning = lambda *a, **k: False  # isolasi side-effect

            worker._run_playground()

            self.assertTrue(state["recover_called"])
            self.assertIn("recovered online", worker.session.code)
            self.assertTrue(worker.session.is_active)
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_loading_then_online_continue_generation(self) -> None:
        worker = self._new_worker()
        try:
            state = {"wait_called": False}
            worker._check_server_online = lambda: (False, "loading")

            def _wait_ready(timeout_seconds: int = 180, poll_interval: float = 1.0):
                state["wait_called"] = True
                return True, "ok"

            worker._wait_until_server_ready = _wait_ready
            worker._call_llm = lambda _prompt: "```python\nprint('generated by ai')\n```"
            worker._capture_learning = lambda *a, **k: False  # isolasi side-effect

            worker._run_playground()

            self.assertTrue(state["wait_called"])
            self.assertIn("generated by ai", worker.session.code)
            self.assertTrue(worker.session.is_active)
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_loading_timeout_must_error_and_auto_close(self) -> None:
        worker = self._new_worker()
        try:
            errors: list[str] = []
            worker.error_signal.connect(errors.append)
            worker._check_server_online = lambda: (False, "loading")
            worker._wait_until_server_ready = lambda timeout_seconds=180, poll_interval=1.0: (False, "loading_timeout")
            worker._call_llm = lambda _prompt: "SHOULD_NOT_BE_CALLED"

            worker._run_playground()

            self.assertFalse(worker.session.is_active)
            self.assertTrue(errors)
            self.assertIn("melewati batas waktu", errors[-1].lower())
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_online_but_llm_empty_must_error_and_auto_close(self) -> None:
        worker = self._new_worker()
        try:
            errors: list[str] = []
            worker.error_signal.connect(errors.append)
            worker._check_server_online = lambda: (True, "ok")
            worker._call_llm = lambda _prompt: ""

            worker._run_playground()

            self.assertFalse(worker.session.is_active)
            self.assertEqual("", worker.session.code)
            self.assertTrue(errors)
            self.assertIn("tanpa template fallback", errors[-1].lower())
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_successful_generation_captures_learning(self) -> None:
        worker = self._new_worker("buat kalkulator tambah kurang")
        try:
            captured: list[tuple[str, str, str]] = []
            worker._check_server_online = lambda: (True, "ok")
            worker._call_llm = lambda _prompt: "```python\nprint('ai output')\n```"
            worker._capture_learning = lambda intent, code, lang: captured.append(
                (intent, code, lang)
            ) or True

            worker._run_playground()

            self.assertTrue(worker.session.is_active)
            self.assertEqual(1, len(captured))
            self.assertIn("ai output", captured[0][1])
            self.assertEqual("python", captured[0][2])
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_fail_close_does_not_capture_learning(self) -> None:
        worker = self._new_worker()
        try:
            captured: list[tuple[str, str, str]] = []
            worker._check_server_online = lambda: (False, "offline")
            worker._attempt_server_recovery = lambda: (False, "offline")
            worker._capture_learning = lambda intent, code, lang: captured.append(
                (intent, code, lang)
            ) or True

            worker._run_playground()

            self.assertFalse(worker.session.is_active)
            self.assertEqual([], captured)
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_capture_learning_writes_template_to_storage(self) -> None:
        worker = self._new_worker("buat kalkulator tambah kurang")
        try:
            with tempfile.TemporaryDirectory(prefix="moko_learn_test_") as storage:
                worker._learning_storage_dir = storage
                ok = worker._capture_learning(
                    "buat kalkulator tambah kurang",
                    "# PLAYGROUND\nprint('hello from ai')\n",
                    "python",
                )
                self.assertTrue(ok)

                from moko_template_learning import TemplateLearningEngine

                engine = TemplateLearningEngine(storage_dir=storage)
                templates = engine.list_templates("kalkulator")
                self.assertTrue(templates)
                self.assertTrue(any(t.origin == "generated" for t in templates))
        finally:
            if worker.session.is_active:
                worker.session.cleanup()

    def test_capture_learning_non_python_is_skipped(self) -> None:
        worker = self._new_worker("buat script bash")
        try:
            with tempfile.TemporaryDirectory(prefix="moko_learn_skip_") as storage:
                worker._learning_storage_dir = storage
                result = worker._capture_learning("buat script bash", "echo hi", "bash")
                self.assertFalse(result)
        finally:
            if worker.session.is_active:
                worker.session.cleanup()


if __name__ == "__main__":
    unittest.main()
