import tempfile
import unittest
from pathlib import Path

from moko_template_learning import TemplateLearningEngine


BASE_TEMPLATE = """import re


def kalkulator():
    print(\"  🔢 MOKO Kalkulator Playground\")
    print(\"Operasi: +  -  *  /  **  %\")


if __name__ == \"__main__\":
    kalkulator()
"""


class TemplateLearningEngineTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tempdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tempdir.cleanup)
        self.engine = TemplateLearningEngine(Path(self.tempdir.name) / "memory")

    def test_register_template_rejects_empty_code(self) -> None:
        with self.assertRaises(ValueError):
            self.engine.register_template("kalkulator", "   ")

    def test_generate_code_personalized_not_raw_copy(self) -> None:
        template = self.engine.register_template("kalkulator", BASE_TEMPLATE)
        generated_code, record = self.engine.generate_code(
            "buat kalkulator tambah kurang bagi untuk siswa",
            "kalkulator",
        )

        self.assertNotEqual(generated_code.strip(), template.code.strip())
        self.assertIn("transform-template-not-copy", generated_code)
        self.assertIn("kalkulator_tambah_kurang", generated_code)
        self.assertEqual(record.source_template_id, template.template_id)
        self.assertTrue(record.generated_template_id)

    def test_learning_record_written_each_generation(self) -> None:
        self.engine.register_template("kalkulator", BASE_TEMPLATE)

        self.engine.generate_code("buat kalkulator tambah", "kalkulator")
        self.engine.generate_code("buat kalkulator pangkat", "kalkulator")

        records = self.engine.list_learning_records()
        self.assertEqual(len(records), 2)
        self.assertTrue(all(record.generated_code for record in records))

    def test_generate_with_no_template_uses_builtin(self) -> None:
        generated_code, record = self.engine.generate_code("buat kalkulator modulo", "kalkulator")

        self.assertIn("Auto-generated by MOKO Template Learning Engine", generated_code)
        self.assertIn("def evaluate_expression", generated_code)
        self.assertNotIn("result = eval(", generated_code)
        self.assertEqual(record.source_template_id, "builtin:kalkulator")

    def test_formula_intent_injects_geometry_formulas(self) -> None:
        generated_code, _record = self.engine.generate_code(
            "buat kalkulator dengan rumus luas persegi panjang dan luas persegi",
            "kalkulator",
        )

        self.assertIn("def hitung_luas_persegi_panjang", generated_code)
        self.assertIn("def hitung_luas_persegi", generated_code)

    def test_generated_code_contains_focus_log_related_to_intent(self) -> None:
        generated_code, _record = self.engine.generate_code(
            "buat kalkulator coding kompleks dengan rumus geometri dan trigonometri",
            "kalkulator",
        )

        self.assertIn("# retrieval_focus:", generated_code)
        self.assertIn("geometri", generated_code.lower())
        self.assertIn("trigonometri", generated_code.lower())

    def test_statistics_intent_injects_relevant_domain(self) -> None:
        generated_code, _record = self.engine.generate_code(
            "buat kalkulator statistika rata rata median dan standar deviasi",
            "kalkulator",
        )

        self.assertIn("def hitung_rata_rata", generated_code)
        self.assertIn("def hitung_standar_deviasi", generated_code)
        self.assertIn("import statistics", generated_code)
        self.assertIn("# knowledge_sources: statistika", generated_code)

    def test_finance_intent_injects_relevant_domain(self) -> None:
        generated_code, _record = self.engine.generate_code(
            "buat kalkulator cicilan pinjaman dengan bunga majemuk",
            "kalkulator",
        )

        self.assertIn("def hitung_bunga_majemuk", generated_code)
        self.assertIn("def hitung_cicilan_bulanan", generated_code)
        self.assertIn("finansial", generated_code)

    def test_unrelated_intent_does_not_inject_knowledge(self) -> None:
        generated_code, _record = self.engine.generate_code(
            "buat kalkulator tambah kurang untuk siswa",
            "kalkulator",
        )

        self.assertIn("# knowledge_sources: none", generated_code)
        self.assertNotIn("def hitung_luas_persegi", generated_code)


if __name__ == "__main__":
    unittest.main()
